return {
  -- 'mrjones2014/legendary.nvim',
  -- dependencies = { 'kkharji/sqlite.lua' },
  -- version = 'v2.1.0',
  -- -- since legendary.nvim handles all your keymaps/commands,
  -- -- its recommended to load legendary.nvim before other plugins
  -- priority = 10000,
  -- lazy = false,
  -- opts = {
  --   lazy_nvim = {
  --     auto_register = true
  --   },
  --   keymaps = {
  --   },
  --   autocmds = {
  --     {
  --       name = 'YankHighlight',
  --       clear = true,
  --       {
  --         'TextYankPost',
  --         function()
  --           vim.highlight.on_yank()
  --         end,
  --         opts = {
  --           pattern = '*',
  --         }
  --       },
  --     },
  --   },
  --   which_key = {
  --     auto_register = true,
  --     mappings = {},
  --     opts = {},
  --     do_binding = true,
  --     use_groups = true,
  --   },
  -- }
};
